//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.01 at 10:35:08 AM EST 
//


package au.com.iglooit.winerymap.converttool;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clueid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fullpath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="theme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="middle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseURI">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="bucketBaseURI">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="bucketName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="WineryInfoDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="winemaker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="wineryards" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="facsimilie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clueid",
    "fullpath",
    "theme",
    "middle",
    "baseURI",
    "wineryInfoDetails"
})
@XmlRootElement(name = "extraction")
public class Extraction {

    protected int clueid;
    @XmlElement(required = true)
    protected String fullpath;
    @XmlElement(required = true)
    protected String theme;
    @XmlElement(required = true)
    protected String middle;
    @XmlElement(required = true)
    protected Extraction.BaseURI baseURI;
    @XmlElement(name = "WineryInfoDetails", required = true)
    protected Extraction.WineryInfoDetails wineryInfoDetails;

    /**
     * Gets the value of the clueid property.
     *
     */
    public int getClueid() {
        return clueid;
    }

    /**
     * Sets the value of the clueid property.
     *
     */
    public void setClueid(int value) {
        this.clueid = value;
    }

    /**
     * Gets the value of the fullpath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFullpath() {
        return fullpath;
    }

    /**
     * Sets the value of the fullpath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFullpath(String value) {
        this.fullpath = value;
    }

    /**
     * Gets the value of the theme property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTheme(String value) {
        this.theme = value;
    }

    /**
     * Gets the value of the middle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMiddle() {
        return middle;
    }

    /**
     * Sets the value of the middle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMiddle(String value) {
        this.middle = value;
    }

    /**
     * Gets the value of the baseURI property.
     *
     * @return
     *     possible object is
     *     {@link Extraction.BaseURI }
     *
     */
    public Extraction.BaseURI getBaseURI() {
        return baseURI;
    }

    /**
     * Sets the value of the baseURI property.
     *
     * @param value
     *     allowed object is
     *     {@link Extraction.BaseURI }
     *
     */
    public void setBaseURI(Extraction.BaseURI value) {
        this.baseURI = value;
    }

    /**
     * Gets the value of the wineryInfoDetails property.
     *
     * @return
     *     possible object is
     *     {@link Extraction.WineryInfoDetails }
     *
     */
    public Extraction.WineryInfoDetails getWineryInfoDetails() {
        return wineryInfoDetails;
    }

    /**
     * Sets the value of the wineryInfoDetails property.
     *
     * @param value
     *     allowed object is
     *     {@link Extraction.WineryInfoDetails }
     *
     */
    public void setWineryInfoDetails(Extraction.WineryInfoDetails value) {
        this.wineryInfoDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="bucketBaseURI">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="bucketName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bucketBaseURI"
    })
    public static class BaseURI {

        @XmlElement(required = true)
        protected Extraction.BaseURI.BucketBaseURI bucketBaseURI;

        /**
         * Gets the value of the bucketBaseURI property.
         *
         * @return
         *     possible object is
         *     {@link Extraction.BaseURI.BucketBaseURI }
         *
         */
        public Extraction.BaseURI.BucketBaseURI getBucketBaseURI() {
            return bucketBaseURI;
        }

        /**
         * Sets the value of the bucketBaseURI property.
         *
         * @param value
         *     allowed object is
         *     {@link Extraction.BaseURI.BucketBaseURI }
         *
         */
        public void setBucketBaseURI(Extraction.BaseURI.BucketBaseURI value) {
            this.bucketBaseURI = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="bucketName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bucketName",
            "uri"
        })
        public static class BucketBaseURI {

            @XmlElement(required = true)
            protected String bucketName;
            @XmlElement(required = true)
            protected String uri;

            /**
             * Gets the value of the bucketName property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getBucketName() {
                return bucketName;
            }

            /**
             * Sets the value of the bucketName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setBucketName(String value) {
                this.bucketName = value;
            }

            /**
             * Gets the value of the uri property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getUri() {
                return uri;
            }

            /**
             * Sets the value of the uri property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setUri(String value) {
                this.uri = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="winemaker" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="wineryards" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="facsimilie" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class WineryInfoDetails {

        @XmlElement(required = true)
        protected Extraction.WineryInfoDetails.Item item;

        /**
         * Gets the value of the item property.
         *
         * @return
         *     possible object is
         *     {@link Extraction.WineryInfoDetails.Item }
         *
         */
        public Extraction.WineryInfoDetails.Item getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         *
         * @param value
         *     allowed object is
         *     {@link Extraction.WineryInfoDetails.Item }
         *
         */
        public void setItem(Extraction.WineryInfoDetails.Item value) {
            this.item = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="winemaker" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="wineryards" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="facsimilie" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "region",
            "address1",
            "address2",
            "website",
            "telephone",
            "winemaker",
            "wineryards",
            "facsimilie",
            "description"
        })
        public static class Item {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String region;
            @XmlElement(required = true)
            protected String address1;
            @XmlElement(required = true)
            protected String address2;
            @XmlElement(required = true)
            protected String website;
            @XmlElement(required = true)
            protected String telephone;
            @XmlElement(required = true)
            protected String winemaker;
            @XmlElement(required = true)
            protected String wineryards;
            @XmlElement(required = true)
            protected String facsimilie;
            @XmlElement(required = true)
            protected String description;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the region property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegion() {
                return region;
            }

            /**
             * Sets the value of the region property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegion(String value) {
                this.region = value;
            }

            /**
             * Gets the value of the address1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress1() {
                return address1;
            }

            /**
             * Sets the value of the address1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress1(String value) {
                this.address1 = value;
            }

            /**
             * Gets the value of the address2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress2() {
                return address2;
            }

            /**
             * Sets the value of the address2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress2(String value) {
                this.address2 = value;
            }

            /**
             * Gets the value of the website property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWebsite() {
                return website;
            }

            /**
             * Sets the value of the website property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWebsite(String value) {
                this.website = value;
            }

            /**
             * Gets the value of the telephone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTelephone() {
                return telephone;
            }

            /**
             * Sets the value of the telephone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTelephone(String value) {
                this.telephone = value;
            }

            /**
             * Gets the value of the winemaker property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWinemaker() {
                return winemaker;
            }

            /**
             * Sets the value of the winemaker property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWinemaker(String value) {
                this.winemaker = value;
            }

            /**
             * Gets the value of the wineryards property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWineryards() {
                return wineryards;
            }

            /**
             * Sets the value of the wineryards property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWineryards(String value) {
                this.wineryards = value;
            }

            /**
             * Gets the value of the facsimilie property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFacsimilie() {
                return facsimilie;
            }

            /**
             * Sets the value of the facsimilie property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFacsimilie(String value) {
                this.facsimilie = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

        }

    }

}
